repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
    -   id: shellcheck
-   repo: https://github.com/thlorenz/doctoc.git
    rev: v2.5.0
    hooks:
    -   id: doctoc
        name: Add TOC for md files
        files: \.md$
        args:
          - "--maxlevel"
          - "4"
          - "--title"
          - "**Table of Contents**"
-   repo: local
    hooks:
    -   id: no-input-eval
        name: Inputs must be compared, not executed
        language: pygrep
        entry: '(if|elif|while|until) +"?\$\{?INPUT_'
        files: ^start\.sh$
